# Generated by Django 4.0.6 on 2022-07-18 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_set_unique_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]

