# Generated by Django 4.0.6 on 2022-07-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_set_unique_true_on_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforeignkeymodel',
            name='test_model_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_model_uuid', to='test_app.testmodel', to_field='uuid'),
        ),
    ]
