# Generated by Django 4.0.6 on 2022-07-18 09:49

from django.db import migrations


def fill_uuid_fk(apps, schema_editor):
    TestForeignKeyModel = apps.get_model('test_app', 'TestForeignKeyModel')

    for instance in TestForeignKeyModel.objects.all():
        instance.test_model_uuid = instance.test_model
        instance.save(update_fields=['test_model_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_testforeignkeymodel_test_model_uuid'),
    ]

    operations = [migrations.RunPython(fill_uuid_fk, reverse_code=migrations.RunPython.noop)]
