# Generated by Django 4.0.6 on 2022-07-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_uuid_fk_test_foreign_key_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Test Through Model',
            },
        ),
        migrations.AddField(
            model_name='testmanytomanymodel',
            name='test_models_uuid',
            field=models.ManyToManyField(related_name='test_manytomany_models_uuid', through='test_app.TestThroughModel', to='test_app.testmodel'),
        ),
        migrations.AddField(
            model_name='testthroughmodel',
            name='test_many_to_many_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.testmanytomanymodel'),
        ),
        migrations.AddField(
            model_name='testthroughmodel',
            name='test_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.testmodel', to_field='uuid'),
        ),
    ]
