# Generated by Django 4.0.6 on 2022-07-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_uuid_m2m_testmanytomanymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforeignkeymodel',
            name='test_model',
        ),
        migrations.RemoveField(
            model_name='testmanytomanymodel',
            name='test_models',
        ),
    ]
