# Generated by Django 4.0.6 on 2022-07-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_remove_testforeignkeymodel_test_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforeignkeymodel',
            name='test_model_uuid',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_model_uuid', to='test_app.testmodel', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='testthroughmodel',
            name='test_model',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.testmodel', to_field='uuid'),
        ),
    ]
