# Generated by Django 4.0.6 on 2022-07-18 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_alter_testforeignkeymodel_test_model_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='testforeignkeymodel',
            name='test_model_uuid',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_model_uuid', to='test_app.testmodel'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testthroughmodel',
            name='test_model',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.testmodel'),
        ),
    ]
