# Generated by Django 4.0.6 on 2022-07-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_remove_testmodel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testforeignkeymodel',
            old_name='test_model_uuid',
            new_name='test_model',
        ),
        migrations.RenameField(
            model_name='testmanytomanymodel',
            old_name='test_models_uuid',
            new_name='test_models',
        ),
    ]
