# Generated by Django 4.0.6 on 2022-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_testforeignkeymodel_test_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmanytomanymodel',
            name='test_models_old',
            field=models.ManyToManyField(related_name='test_manytomany_models_old', to='test_app.testmodel'),
        ),
    ]
