# Generated by Django 4.0.6 on 2022-07-18 10:29

from django.db import migrations


def copy_m2m(apps, schema_editor):
    TestManyToManyModel = apps.get_model('test_app', 'TestManyToManyModel')

    for instance in TestManyToManyModel.objects.all():
        for test_model in instance.test_models.all():
            instance.test_models_old.add(test_model)


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_testmanytomanymodel_test_models_old'),
    ]

    operations = [migrations.RunPython(copy_m2m, reverse_code=migrations.RunPython.noop)]
