# Generated by Django 4.0.6 on 2022-07-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_copy_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmanytomanymodel',
            name='test_models',
        ),
        migrations.DeleteModel(
            name='TestThroughModel',
        ),
    ]
