# Generated by Django 4.0.6 on 2022-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_rename_test_models_old_testmanytomanymodel_test_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmanytomanymodel',
            name='test_models',
            field=models.ManyToManyField(related_name='test_manytomany_models', to='test_app.testmodel'),
        ),
    ]
